---
- name: "Networking: Ensure interfaces.d inclusion in main interfaces file"
  ansible.builtin.lineinfile:
    path: /etc/network/interfaces
    line: "source /etc/network/interfaces.d/*"
    state: present
    insertafter: EOF

- name: "Networking: Ensure DMZ bridge is configured in network interfaces"
  ansible.builtin.template:
    src: dmz_bridge.cfg.j2
    dest: "/etc/network/interfaces.d/{{ dmz_bridge_name }}.cfg"
    owner: root
    group: root
    mode: '0644'
  notify: Reload network interfaces
