---
- name: "Networking: Cleanup legacy DMZ bridge config from interfaces.d"
  ansible.builtin.file:
    path: "/etc/network/interfaces.d/{{ dmz_bridge_name }}.cfg"
    state: absent

- name: "Networking: Ensure DMZ bridge is configured in main interfaces file"
  ansible.builtin.blockinfile:
    path: /etc/network/interfaces
    marker: "# {mark} ALCAMBIC MANAGED BLOCK - DMZ BRIDGE"
    insertbefore: "^source /etc/network/interfaces.d/.*"
    block: "{{ lookup('ansible.builtin.template', 'dmz_bridge.cfg.j2') + '\n' }}"
  notify: Reload network interfaces
