---
- name: "Day-0 Phase 1.1: Proxmox VE Bootstrap"
  hosts: proxmox_cluster
  remote_user: root
  become: no
  vars:
    ansible_ssh_private_key_file: ""
  roles:
    - initial_setup

- name: "Day-0 Phase 1.2: Proxmox VE Configuration & Hardening"
  hosts: proxmox_cluster
  roles:
    - role: secure_ssh
      vars:
        ssh_permit_root_login: "prohibit-password"
    - pve_firewall
    - networking
    - role: pve_api_rbac
      run_once: true
      vars:
        rbac_user: "alcambic-tofu-provisioner@pve"
        rbac_comment: "Automated provisioning account for OpenTofu in Alcambic project"
        rbac_token_name: "devbox"
        rbac_secret_dest: "./proxmox_api_token_tofu.txt"
        rbac_vault_var_name: "vault_pve_api_tofu_token"
        rbac_vaulted_token: "{{ vault_pve_api_tofu_token | default('') }}"
