---
- name: Day-0 Proxmox VE Bootstrap
  hosts: proxmox_cluster
  gather_facts: yes
  remote_user: root

  roles:
    - initial_setup

- name: Day-0 Proxmox VE Configuration & Hardening
  hosts: proxmox_cluster
  gather_facts: yes
  remote_user: alcambic
  become: yes

  tasks:
    - name: "Smoke Test: Verify SSH connectivity and sudo escalation for service account"
      ansible.builtin.ping:

  # roles:
  #   - networking
  #   - pve_firewall
  #   - secure_ssh
